F05 - PR 1
inesmokaddem/crazee-burger pull request #5
Opened 2023-03-23 14:34 UTC by inesmokaddem

2023-03-24 12:17 UTC, simoncdna commented on src/components/reusable-ui/Card.js
> +      <CardStyled className="produit">
Attention au naming en francais. De plus, ici il n'est pas utile vu que tu définis ton style avec CardStyled de styled-component

2023-03-25 15:57 UTC, vileaddev requested changes
Je suis d'accord mais corrections sur l'UI à ajouter

2023-03-25 15:57 UTC, vileaddev commented on src/components/pages/order/main/Menu.js
> +    <MenuStyled className="menu">
```suggestion
    <MenuStyled>
```

2023-03-25 15:57 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +        <div className="product__img">
```suggestion
        <div className="product-img">
```

2023-03-27 11:34 UTC, merged