F06 - PR 1
inesmokaddem/crazee-burger pull request #6
Opened 2023-03-27 14:41 UTC by inesmokaddem

2023-03-27 17:01 UTC, Ovgodd commented on src/components/pages/order/navbar/NavbarRightSide.js
> +  const [isModeAdmin, setIsModeAdmin] = useState(false);
isAdmin, setIsAdmin devrait suffire je pense, on comprends de suite 

"isAdmin" > est-on en admin ?
"isModeAdmin" > est-on en mode admin ? 

cela veux dire la même chose mais le premier et plus court et concis à mon sens

```suggestion
  const [isAdmin, setIsAdmin] = useState(false);
```

2023-03-27 17:01 UTC, Ovgodd commented on src/components/pages/order/navbar/NavbarRightSide.js
>  export default function NavbarRigthSide({username}) {
Petit détail : Eventuellement appeler ton composant juste "RightSide" car en soit il "NavbarRightSide", est déjà dans un composant parent "NavBar".
Cela te ferais une architecture de composant plus clean et moins dense niveau naming je pense !

```suggestion
export default function RightSide({username}) {
```

2023-03-27 17:01 UTC, Ovgodd commented on src/components/pages/order/navbar/NavbarRightSide.js
> +    if (!isModeAdmin) {
```suggestion
    if (!isAdmin) {
```
( si renaming validé par Vi )

2023-03-27 17:01 UTC, Ovgodd commented on src/components/pages/order/navbar/NavbarRightSide.js
> +    setIsModeAdmin(!isModeAdmin)
```suggestion
    setIsAdmin(!isAdmin)
```
( si renaming validé par Vi )

2023-03-27 17:21 UTC, DavidRelut commented on src/components/pages/order/navbar/NavbarRightSide.js
>  export default function NavbarRigthSide({username}) {
Ta props `username` que tu fais passer de composant en composant (OrderPage > Navbar > NavbarRightSide > Profile)
Tu peux directement la consommer là où tu en à besoin en l'occurrence dans ton composant `<Profile />`

2023-03-27 18:45 UTC, vileaddev commented on src/components/pages/order/navbar/NavbarRightSide.js
> +  const [isModeAdmin, setIsModeAdmin] = useState(false);
En principe, je suis d'accord avec toi @Ovgodd 💯 
Après, si @inesmokaddem préfère isModeAdmin, ça, à la liiimite, ça peut passer car c'est pas hyper long et si c'est plus clair pour elle. Là c'est les gouts et les couleurs. Mais si c'était hyper long, oui, faut essayer de raccourcir autant que possible **sans perdre le sens**.

2023-03-27 18:46 UTC, vileaddev commented on src/components/pages/order/navbar/NavbarRightSide.js
>  export default function NavbarRigthSide({username}) {
> Petit détail : Eventuellement appeler ton composant juste "RightSide" car en soit il "NavbarRightSide", est déjà dans un composant parent "NavBar". Cela te ferais une architecture de composant plus clean et moins dense niveau naming je pense !

C'est vrai, tu as raison @Ovgodd 💯

2023-03-27 18:47 UTC, vileaddev commented on src/components/pages/order/navbar/NavbarRightSide.js
>  export default function NavbarRigthSide({username}) {
> 

Je suis d'accord avec toi aussi @DavidRelut  💯

2023-03-27 18:53 UTC, vileaddev requested changes
Les autres t'ont laissé des commentaires pour optimiser ton code. Je suis d'accord avec eux et d'ailleurs par la suite dans les tickets d'après, je me corrige dans ce sens justement 💯

2023-03-29 17:37 UTC, vileaddev approved these changes
Tu peux merge ✅

2023-03-29 17:38 UTC, merged