F07
inesmokaddem/crazee-burger pull request #7
Opened 2023-03-31 14:58 UTC by inesmokaddem

2023-03-31 15:31 UTC, TomFSC commented on src/components/pages/order/OrderPage.js
> +    currentSelectedTab,
```suggestion
    currentTabSelected,
```
plutôt dans ce sens 😄

2023-03-31 15:32 UTC, TomFSC commented on src/components/pages/order/OrderPage.js
> +    setCurrentSelectedTab,
Et du coup 
```suggestion
    setCurrentTabSelected,
```

2023-03-31 15:37 UTC, TomFSC commented on src/components/pages/order/main/Admin/AdminTabs.js
> +        margin-left: 1px;
Attention aux "magic strings", utilise le theme, tu peux adapter si besoin (ex : pour le 1px tu peux créer une constante)

2023-03-31 15:47 UTC, TomFSC commented on src/components/pages/order/main/Admin/AdminBloc.js
> +export default function AdminBloc() {
```suggestion
export default function Admin() {
```
tout simplement 😄 , ou quelque chose de plus explicite peut-être

2023-03-31 16:53 UTC, vileaddev requested changes

2023-03-31 16:53 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminBloc.js
> +export default function AdminBloc() {
AdminBloc pourrait faire penser à la partie en dessous, donc c'est vrai que Admin serait plus adapté ici, au même titre que Menu ou Basket qui restent général pour tout contenir.

2023-03-31 16:53 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminTabs.js
> +        margin-left: 1px;
Rigoureusement tu as raison @TomFSC mais là depuis le début du projet on est moins rigoureux et en entreprise c'est pas mal comme ça aussi 😕  Du coup, moi ça me choque pas trop.

2023-03-31 16:53 UTC, vileaddev commented on src/components/pages/order/main/Admin/TabsLibrary.js
> +export const TabsLibrary = [
c'est étonnant ce nom 🤔

2023-04-05 12:44 UTC, DavidRelut requested changes

2023-04-05 12:44 UTC, DavidRelut commented on src/components/pages/order/main/Admin/AdminTabs.js
> +        {tabs.map((tab) => (
Plutôt que d'accéder à toute les propriétés de ton objet à partir de `tab`, il serait plus judicieux de partir sur une syntaxe en destructuring.
💡 La raison, c'est que si ton app évolue, ton code pourrait devenir moins clair et contenir des erreurs, donc pour cela, partir sur du destructuring permet explicitement d'avoir les propriété dont tu aura besoin ;)

2023-04-05 12:44 UTC, DavidRelut commented on src/context/OrderContext.js
> +    currentSelectedTab: false,
Ce ne serait pas plutôt une string ? 
```suggestion
    currentSelectedTab: "",
```

2023-04-10 12:32 UTC, vileaddev requested changes
attention à la "case" de tabsConfig (≠ TabsConfig)

corriger le CSS au niveau du border bottom de Tab quand le panel est replié.

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel.js
> +  const TabSelected = getTabSelected(tabs, currentTabSelected)
```suggestion
  const tabSelected = getTabSelected(tabs, currentTabSelected)
```
ce n'est pas un composant --> minuscule

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel.js
> +  const tabs = TabsConfig
```suggestion
  const tabs = tabsConfig
```

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/TabsConfig.js
tabsConfig.js (minuscule)

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/TabsConfig.js
> +export const TabsConfig = [
```suggestion
export const tabsConfig = [
```

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminTabs.js
> +  const tabs = TabsConfig
```suggestion
  const tabs = tabsConfig
```

2023-04-10 12:32 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminTabs.js
> +        {tabs.map((tab) => (
```suggestion
        {tabs.map(({index, label, Icon }) => (
```

2023-04-11 15:44 UTC, vileaddev requested changes

2023-04-11 15:44 UTC, vileaddev commented on src/components/pages/order/main/Admin/TabsConfig.js
toujours le titre du fichier à changer

2023-05-16 09:32 UTC, YannLescot requested changes

2023-05-16 09:32 UTC, YannLescot commented on src/components/pages/order/main/Admin/AdminTabs.js
> +  const {isCollapsed, setIsCollapsed, currentTabSelected, setcurrentTabSelected} = useContext(OrderContext)
Peut être passer à isPanelCollapsed pour ajouter plus de clarté à ton state ?

2023-05-16 09:32 UTC, YannLescot commented on src/components/pages/order/main/Admin/AdminTabs.js
> +  const selectTab = (tabSelected) => {
Pourquoi pas renommer ta fonction en handleSelectTab ?

2023-05-16 13:17 UTC, merged