F09
inesmokaddem/crazee-burger pull request #9
Opened 2023-06-14 19:27 UTC by inesmokaddem

2023-06-19 11:28 UTC, YannLescot reviewed
Plein de bonnes choses, concentre toi sur ce qui te semble cohérent et que tu comprends dans mes commentaires. Pour le reste hésite pas à poser toutes les questions qui te viennent, même pour Vi lorsqu'il passera ! 🔥 💪 😁

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/OrderPage.js
Dans ce fichier, tuas un handleAddProduct, mais pour les autres handle tu n'as pas précisé Product. Pour garder une cohérence, mets product partout, ou ne le met nulle part !

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/AdminPanel/EditInfoMessage.js
> +      <span className="live-update">en temps réel</span>
Je me demande si une margin left sur ton span n'est pas mieux qu'un espace virtuel dans ton texte, mais en même temps j'aime bien l'idée car la taille de l'espace restera cohérente à tous les resizes. À voir ce que dit Vi !

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/AdminPanel/EditProductForm.js
> +  }
Tu parles de gestionnaire d'évènement en commentaire, mais tu y manipules du state, et ta fonction commence par "handle" ... 🤔
Pourquoi pas un onEditInputChange (ou onInputChange) qui manipule l'event reçu, passe les bonnes infos et qui appellerai un handleProductUpdate qui lui manipule tes states en ayant les bonnes infos (que ton onEditInputChange a récupéré ?

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/AdminPanel/SubmitButton.js
> +        label={"Ajouter un nouveau produit au menu"}
Une raison particulière pour les accolades ?

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/TabsConfig.js
> +    //   },
Dead code 💀 
Je vois dans quel contexte tu en as eu besoin, mais à l'envoi de ta PR, il est mieux de le clean !

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/TabsConfig.js
> +// }
☠️ ☠️

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Admin/TabsConfig.js
> +        Content: hasAlreadyBeenClicked ? <EditProductForm/> : <HintMessage/>
C'est pas mal, par contre ton getTabsConfig dépend d'une prop à cause de cette ligne précise. J'ai fait la même chose donc y'a pas de souci, mais c'est un élément à prendre en compte quand tu gère des edge cases ou des exceptions ! :)

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Menu/Menu.js
> +  }
Ce n'est pas un gestionnaire d'évènement si tu mets tous tes states dedans ! On est qu'au F09 donc je ne sais pas à quel point c'est clair, et c'est probablement codé comme ça dans les lives, mais c'est important de comprendre la différence entre des gestionnaires d'évènement (onClick, je fais des trucs liés à l'évènement précis du clic, type stopPropagation ou Refresh, et handleState, je gère tous les changements d'état)

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Menu/Menu.js
> +  }
Là c'est un bon exemple, ta ligne 49 n'a pas sa place dans ce gestionnaire d'état car elle gère un edge case du à l'évènement du clic, et pas aux états qui découlent de cette action. Si c'est pas clair hésite pas à le dire ! :)

2023-06-19 11:28 UTC, YannLescot commented on src/components/pages/order/main/Menu/helper.js
> +export const checkIfProductIsClicked  = (idProductInMenu, idProductClickedOn) => {
"isProductSelected" par exemple ? On dit d'un produit qu'il est sélectionné plutôt que cliqué, tu vois ?

2023-06-19 11:28 UTC, YannLescot commented on src/components/reusable-ui/Card.js
> +                  onClick={(event) => event.stopPropagation()}
Là c'est le bon endroit pour le gérer effectivement. Mais pas dans un éventuel handleAddProduct, tu vois ?

2023-06-19 11:28 UTC, YannLescot commented on src/components/reusable-ui/TextInput.js
> +        <div className="icon">{Icon && Icon}</div>
Pourquoi pas plutôt Icon && <div ...>{Icon}</div> ?
Là si tu n'as pas d'icon, tu as quand même créé une div dans ton DOM pour rien. Et dans le cas d'une grid ou quoi ça t'occupe un espace !

2023-06-20 23:37 UTC, vileaddev requested changes
Très bien cette PR @inesmokaddem et très bien les commentaires @YannLescot.
J'ai laissé des remarques pour vous deux 😉

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
>    const handleAddProduct = (newProduct) => {
```suggestion
  const handleAddMenu = (newProduct) => {
```

On **sait** que le basket va arriver quelques tickets plus tard. Change le maintenant. Ca t'évitera de tout changer après. Comme on le "sait", ce n'est pas du YAGNI.

Pense à le changer pour les autres, handleEditMenu, handleDeleteMenu, handleAddMenu, etc.

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel/EditInfoMessage.js
> +      <span className="live-update">en temps réel</span>
Perso, moi ça me va comme ça, je ne suis pas choqué. Le pb du margin et padding, c'est que ça va en effet changer en fonction de la size 😕

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel/EditProductForm.js
> +    handleEdit(productBeingUpdated, event) // cette ligne update le menu
```suggestion
    handleOnChange(productBeingUpdated, event) // cette ligne update le menu
```

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel/EditProductForm.js
> +  }
Pour moi, handleOnChange c'est suffisant.

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/main/Admin/AdminPanel/SubmitButton.js
> +        label={"Ajouter un nouveau produit au menu"}
Je suis d'accord avec @YannLescot 💯

2023-06-20 23:37 UTC, vileaddev commented on src/components/pages/order/main/Menu/Menu.js
> +  }
100% d'accord avec @YannLescot. Regarde bien les live, la différence entre les deux est bien expliquée @inesmokaddem

2023-06-20 23:37 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +                  onClick={(event) => event.stopPropagation()}
Pas forcément d'accord avec toi @YannLescot ici.Je dirais gère le en dehors du composant. "Raise the event". fais remonter l'événement à l'extérieur du composant par le haut et gère cet événement à l'extérieur dans un onAdd externe.

2023-06-20 23:37 UTC, vileaddev commented on src/components/reusable-ui/TextInput.js
> +        <div className="icon">{Icon && Icon}</div>
```suggestion
        {Icon &&  <div className="icon">{Icon}</div>}
```

2023-06-26 17:20 UTC, vileaddev commented on src/components/pages/order/main/Menu/Menu.js
> +  }
En gros, met le dans OrderPage.js

2023-06-26 17:22 UTC, vileaddev commented on src/components/pages/order/main/Menu/Menu.js
> +  }
Cette fois-ci je suis d'accord avec @inesmokaddem. Elle a bien géré le stopPropagation dans un gestionnaire d'événêment et non de state.

2023-06-26 17:55 UTC, vileaddev approved these changes

2023-06-26 17:55 UTC, vileaddev commented on src/components/reusable-ui/Card.js
> +                  onClick={(event) => event.stopPropagation()}
```suggestion
                  onClick={onClick}
```

et ensuite, le onClick que tu envoies en valeur, il te vient des props de Card.js

2023-06-26 17:56 UTC, merged